name: GitHub Actions for jd-gui HistoryTest
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Test HistoryTest
        run: ./gradlew :app:test --tests org.jd.gui.model.history.HistoryTest --info
